### ISSUE TITLE
nr_thread.c에서의 몇 가지 의문과 제기할 점

### ISSUE THREAD

**Issue by kyeongmincho** [SomaLDEN/Event-Notifier#1]
1. 맵을 세 개로 나눴는데 맵을 하나로 두고 value를 structure로 관리하는 게 어떤지..?
2. min을 0으로 초기화 하였는데, 비록 0으로 나올 확률이 전혀 없다하더라도, 애초에 -1로 초기화 하고 -1인지 검사하는 것이 논리적으로 탈이 없는 깔끔한 코드일 것 같다.

**Comment by SunKyu** [comment]
1번 2번 모두 고쳤습니다.
